# Generated by Django 3.1.4 on 2020-12-11 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=300, unique=True)),
                ('branch_name', models.CharField(max_length=300)),
                ('branch_addres', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_name', models.CharField(max_length=300, null=True, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Transactions_ID', models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True, unique=True)),
                ('Item_Id', models.IntegerField()),
                ('Source_Branch', models.CharField(max_length=300)),
                ('Destination_Branch', models.CharField(max_length=300)),
                ('Transaction_Type', models.CharField(max_length=300)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
