# Generated by Django 3.1.4 on 2020-12-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='Destination_Branch',
            new_name='destination_branch',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Item_Id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Source_Branch',
            new_name='source_branch',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Transaction_Type',
            new_name='transaction_type',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='Transactions_ID',
            new_name='transactions_id',
        ),
    ]
