# Generated by Django 3.1.4 on 2020-12-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0003_auto_20201211_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_type',
            field=models.TextField(max_length=300),
        ),
    ]
