# Generated by Django 3.1.4 on 2020-12-12 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0005_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.AddField(
            model_name='inventory',
            name='branch_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.branch', to_field='branch_code'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.item'),
        ),
    ]
