# Generated by Django 3.1.4 on 2020-12-19 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_auto_20201212_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('contractor_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubContractor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SubContractorTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('item_id', models.IntegerField()),
                ('branch', models.CharField(max_length=300)),
                ('contractor_id', models.IntegerField()),
                ('transaction_type', models.TextField(max_length=300)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractorInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('contractor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.subcontractor')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.item')),
            ],
        ),
    ]
